import { normalizeCandidateName, normalizedCandidateKey } from "./candidate-eligibility";
import { researchDb } from "./supabase-rest";

const supportedRelations = new Set(["TREAT", "PREVENT", "INHIBIT", "STIMULATE", "POSITIVE_CORRELATE", "ASSOCIATE", "INFERRED_COOCCURRENCE", "TRIAL_INTERVENTION"]);
type EvidenceRow={id:string;title:string;source_id:string|null}; type RelationRow={evidence_id:string;relation_type:string;entity1_type:string|null;entity1_id:string|null;entity1_text:string|null;entity2_type:string|null;entity2_id:string|null;entity2_text:string|null;source?:string|null}; type QualityRow={evidence_id:string;composite_score:number}; type ExistingCandidate={drug_name:string};
export type GeneratedCandidate={drugName:string;drugNormalizedId?:string;geneName?:string;geneNormalizedId?:string;relationType:string;evidenceIds:string[];evidenceCount:number;meanEvidenceQuality:number;maxEvidenceQuality:number;confidence:number;noveltyScore:number;generationScore:number;hypothesisSummary:string};
const normalize=(v?:string|null)=>v?normalizedCandidateKey(v):""; const isDrug=(t?:string|null)=>["CHEMICAL","DRUG"].includes(t?.toUpperCase()??""); const isGene=(t?:string|null)=>t?.toUpperCase()==="GENE"; const clamp=(v:number)=>Math.max(0,Math.min(100,Math.round(v*10)/10)); const normalizedGene=(v?:string|null)=>v?.toLowerCase().replace(/[^a-z0-9]+/g," ").trim()??""; const identityKey=(name:string,id?:string|null)=>id&&id.trim()?`ID:${id.trim().toUpperCase()}`:`NAME:${normalizedCandidateKey(name)}`; const signature=(drug:string,relation:string,gene?:string|null,id?:string|null)=>`${identityKey(drug,id)}|${relation.toUpperCase()}|${normalizedGene(gene)}`; const therapeuticCue=(title:string)=>/\b(treat|treatment|therapy|therapeutic|trial|randomi[sz]ed|dose|dosing|safety|efficacy|pharmacokinetic|phase\s*[1234ivx]+|repurpos|chaperone)\b/i.test(title);

export async function generateCandidateHypotheses(diseaseName:string){
 const diseases=await researchDb<{id:string}[]>(`research_diseases?canonical_name=eq.${encodeURIComponent(diseaseName)}&select=id`);const diseaseId=diseases[0]?.id;if(!diseaseId)return{generated:0,candidates:[] as GeneratedCandidate[]}; const evidence=await researchDb<EvidenceRow[]>(`research_evidence?disease_id=eq.${diseaseId}&select=id,title,source_id`);if(!evidence.length)return{generated:0,candidates:[] as GeneratedCandidate[]}; const evidenceIds=evidence.map(r=>r.id),evidenceById=new Map(evidence.map(r=>[r.id,r]));
 const [relations,qualities,existingCandidates]=await Promise.all([researchDb<RelationRow[]>(`research_evidence_relations?evidence_id=in.(${evidenceIds.join(",")})&select=evidence_id,relation_type,entity1_type,entity1_id,entity1_text,entity2_type,entity2_id,entity2_text,source`),researchDb<QualityRow[]>(`evidence_quality_scores?evidence_id=in.(${evidenceIds.join(",")})&scoring_version=eq.EQS-1.0&select=evidence_id,composite_score`),researchDb<ExistingCandidate[]>(`repurposing_candidates?disease_id=eq.${diseaseId}&select=drug_name`)]); const qualityByEvidence=new Map(qualities.map(r=>[r.evidence_id,Number(r.composite_score)])),knownDrugs=new Set(existingCandidates.map(r=>normalize(r.drug_name)));
 const grouped=new Map<string,{drugName:string;drugId?:string;geneName?:string;geneId?:string;relationType:string;evidenceIds:Set<string>;qualities:number[];therapeuticCueHits:number;aliases:Set<string>}>();
 for(const relation of relations){const relationType=relation.relation_type.toUpperCase();if(!supportedRelations.has(relationType))continue;let drugName:string|undefined,drugId:string|undefined,geneName:string|undefined,geneId:string|undefined;if(isDrug(relation.entity1_type)){drugName=relation.entity1_text??undefined;drugId=relation.entity1_id??undefined;if(isGene(relation.entity2_type)){geneName=relation.entity2_text??undefined;geneId=relation.entity2_id??undefined;}}else if(isDrug(relation.entity2_type)){drugName=relation.entity2_text??undefined;drugId=relation.entity2_id??undefined;if(isGene(relation.entity1_type)){geneName=relation.entity1_text??undefined;geneId=relation.entity1_id??undefined;}}if(!drugName||normalize(drugName).length<2)continue;const originalName=drugName;drugName=normalizeCandidateName(drugName);const key=signature(drugName,relationType,geneName,drugId);const group=grouped.get(key)??{drugName,drugId,geneName,geneId,relationType,evidenceIds:new Set<string>(),qualities:[],therapeuticCueHits:0,aliases:new Set<string>()};group.aliases.add(originalName);group.evidenceIds.add(relation.evidence_id);const quality=qualityByEvidence.get(relation.evidence_id);if(quality!==undefined)group.qualities.push(quality);const ev=evidenceById.get(relation.evidence_id);if(ev&&therapeuticCue(ev.title))group.therapeuticCueHits++;grouped.set(key,group);}
 const candidates:GeneratedCandidate[]=[...grouped.values()].map(group=>{const evidenceCount=group.evidenceIds.size,meanEvidenceQuality=group.qualities.length?group.qualities.reduce((a,b)=>a+b,0)/group.qualities.length:45,maxEvidenceQuality=group.qualities.length?Math.max(...group.qualities):45,noveltyScore=knownDrugs.has(normalize(group.drugName))?20:85,inferred=group.relationType==="INFERRED_COOCCURRENCE",trial=group.relationType==="TRIAL_INTERVENTION";const relationStrength=trial?72:inferred?(evidenceCount>=3?42:evidenceCount>=2?34:group.therapeuticCueHits>0?31:22):group.relationType==="TREAT"||group.relationType==="PREVENT"?90:group.relationType==="INHIBIT"||group.relationType==="STIMULATE"?75:group.relationType==="POSITIVE_CORRELATE"?65:50,evidenceBreadth=clamp(35+Math.min(evidenceCount,5)*12),confidence=clamp(meanEvidenceQuality*.55+relationStrength*.30+evidenceBreadth*.15),generationScore=clamp(meanEvidenceQuality*.40+noveltyScore*.25+relationStrength*.20+evidenceBreadth*.15),aliasNote=group.aliases.size>1?` Aliases consolidated: ${[...group.aliases].join(", ")}.`:"";const summary=trial?`${group.drugName} is listed as a drug/biological intervention in ClinicalTrials.gov for ${diseaseName} across ${evidenceCount} trial record${evidenceCount===1?"":"s"}.${aliasNote} This establishes clinical investigation, not efficacy.`:inferred?`${group.drugName} co-occurs with ${diseaseName}${group.geneName?` and ${group.geneName}`:""} across ${evidenceCount} evidence record${evidenceCount===1?"":"s"}.${aliasNote} This is a discovery signal only; no causal or treatment relationship is asserted.`:`${group.drugName} has a ${group.relationType} evidence signal in ${diseaseName}${group.geneName?` involving ${group.geneName}`:""}.${aliasNote} This is a machine-generated research hypothesis requiring scientific review.`;return{drugName:group.drugName,drugNormalizedId:group.drugId,geneName:group.geneName,geneNormalizedId:group.geneId,relationType:group.relationType,evidenceIds:[...group.evidenceIds],evidenceCount,meanEvidenceQuality:clamp(meanEvidenceQuality),maxEvidenceQuality:clamp(maxEvidenceQuality),confidence,noveltyScore,generationScore,hypothesisSummary:summary};}).filter(c=>c.relationType==="TRIAL_INTERVENTION"?c.generationScore>=50:c.relationType==="INFERRED_COOCCURRENCE"?(c.evidenceCount>=2&&c.generationScore>=50)||(c.evidenceCount===1&&c.maxEvidenceQuality>=70&&c.generationScore>=50):c.generationScore>=45).sort((a,b)=>b.generationScore-a.generationScore).slice(0,100);
 for(const candidate of candidates){const canonical=normalizeCandidateName(candidate.drugName);const gene=normalizedGene(candidate.geneName);const matches=await researchDb<Array<{id:string;drug_name:string;gene_name:string|null}>>(`generated_candidate_hypotheses?disease_id=eq.${diseaseId}&relation_type=eq.${encodeURIComponent(candidate.relationType)}&select=id,drug_name,gene_name`);const existing=matches.find(r=>normalize(r.drug_name)===normalize(canonical)&&normalizedGene(r.gene_name)===gene);const row={disease_id:diseaseId,drug_name:canonical,drug_normalized_id:candidate.drugNormalizedId??null,gene_name:candidate.geneName??null,gene_normalized_id:candidate.geneNormalizedId??null,relation_type:candidate.relationType,hypothesis_summary:candidate.hypothesisSummary,support_evidence_ids:candidate.evidenceIds,evidence_count:candidate.evidenceCount,mean_evidence_quality:candidate.meanEvidenceQuality,max_evidence_quality:candidate.maxEvidenceQuality,confidence:candidate.confidence,novelty_score:candidate.noveltyScore,generation_score:candidate.generationScore,updated_at:new Date().toISOString()};if(existing)await researchDb<unknown>(`generated_candidate_hypotheses?id=eq.${existing.id}`,{method:"PATCH",body:row,prefer:"return=minimal"});else await researchDb<unknown>("generated_candidate_hypotheses",{method:"POST",body:row,prefer:"return=minimal"});}
 return{generated:candidates.length,candidates};
}
