import { assessCandidateEligibility, normalizedCandidateKey } from "./candidate-eligibility";
import { researchDb } from "./supabase-rest";

const positiveRelations = new Set(["TREAT", "PREVENT", "INHIBIT", "STIMULATE", "POSITIVE_CORRELATE", "ASSOCIATE", "TRIAL_INTERVENTION"]);
const negativeRelations = new Set(["CAUSE", "NEGATIVE_CORRELATE"]);
type GeneratedRow = { id:string; disease_id:string; drug_name:string; drug_normalized_id:string|null; relation_type:string; evidence_count:number; mean_evidence_quality:number; confidence:number; novelty_score:number };
type RelationRow = { evidence_id:string; relation_type:string; entity1_type:string|null; entity1_id:string|null; entity1_text:string|null; entity2_type:string|null; entity2_id:string|null; entity2_text:string|null };
type EvidenceRow = { id:string; disease_id:string; title:string; evidence_class:string };
type ExistingCandidate = { disease_id:string; drug_name:string };
type LandscapeFact = { disease_id:string|null; drug_name:string; drug_normalized_id:string|null; fact_type:string; confidence:number };
const normalize = (v?:string|null) => v ? normalizedCandidateKey(v) : "";
const clamp = (v:number) => Math.max(0, Math.min(100, Math.round(v*10)/10));
const isDrug = (t?:string|null) => ["CHEMICAL","DRUG"].includes(t?.toUpperCase() ?? "");
const keyFor = (name:string,id?:string|null) => id ? `ID:${id}` : `NAME:${normalize(name)}`;
const identityKey = (c:GeneratedRow) => `${c.disease_id}|${normalize(c.drug_name)}|${c.relation_type.toUpperCase()}`;
function relationDrug(r:RelationRow){ if(isDrug(r.entity1_type)) return {name:r.entity1_text??"",id:r.entity1_id}; if(isDrug(r.entity2_type)) return {name:r.entity2_text??"",id:r.entity2_id}; }
function exposureScore(evidence:EvidenceRow[], drugName:string, facts:LandscapeFact[]){ const drug=normalize(drugName); let score=20; const hits=evidence.filter(e=>drug && normalize(e.title).includes(drug)); if(hits.length) score=30; for(const e of hits){ if(e.evidence_class==="E1") score+=25; else if(["E2","E3"].includes(e.evidence_class)) score+=15; else if(["E4","E5"].includes(e.evidence_class)) score+=8; if(/phase\s*(3|iii)|randomi[sz]ed|approved|safety|pharmacokinetic|\bpk\b|dose/i.test(e.title)) score+=8; } for(const f of facts) if(["HUMAN_EXPOSURE","APPROVAL","KNOWN_INDICATION","APPROVED_INDICATION","ACTIVE_TRIAL"].includes(f.fact_type)) score += 10*(Number(f.confidence)/100); return clamp(score); }
function landscapePenalty(facts:LandscapeFact[]){ let competition=0, negative=0; for(const f of facts){ const w=Number(f.confidence)/100; if(f.fact_type==="KNOWN_INDICATION") competition+=25*w; if(["APPROVAL","APPROVED_INDICATION"].includes(f.fact_type)) competition+=30*w; if(f.fact_type==="ACTIVE_TRIAL") competition+=18*w; if(f.fact_type==="COMPETITOR_ASSET") competition+=25*w; if(f.fact_type==="IP_CONSTRAINT") competition+=30*w; if(f.fact_type==="NEGATIVE_TRIAL") negative+=45*w; if(f.fact_type==="SAFETY_SIGNAL") negative+=35*w; } return {competition:clamp(competition),negative:clamp(negative)}; }
function route(score:number,negative:number,competition:number){ if(negative>=60)return "DEPRIORITIZE" as const; if(score>=75&&competition<45)return "FAST_TRACK_DRA" as const; if(score>=60)return "DRA_REVIEW" as const; if(score>=45)return "HOLD" as const; return "DEPRIORITIZE" as const; }
async function deduplicateGenerated(rows:GeneratedRow[]) { const best=new Map<string,GeneratedRow>(); const duplicates:GeneratedRow[]=[]; for(const row of rows){const key=identityKey(row);const current=best.get(key);if(!current){best.set(key,row);continue;}const rs=Number(row.evidence_count)*100+Number(row.confidence);const cs=Number(current.evidence_count)*100+Number(current.confidence);if(rs>cs){duplicates.push(current);best.set(key,row);}else duplicates.push(row);} for(const duplicate of duplicates)await researchDb<unknown>(`generated_candidate_hypotheses?id=eq.${duplicate.id}`,{method:"PATCH",prefer:"return=minimal",body:{status:"SUPERSEDED",routing_decision:"DEPRIORITIZE",ranking_version:"CRN-2.2",updated_at:new Date().toISOString()}}); return [...best.values()]; }

export async function rankGeneratedCandidatesV2(diseaseName?:string){
  const filter=diseaseName?`&canonical_name=eq.${encodeURIComponent(diseaseName)}`:""; const diseases=await researchDb<Array<{id:string;canonical_name:string}>>(`research_diseases?select=id,canonical_name${filter}`); const diseaseIds=diseases.map(d=>d.id); if(!diseaseIds.length)return{ranked:0,fastTrack:0,review:0}; const inDiseases=`(${diseaseIds.join(",")})`;
  const [generatedRaw,evidence,existing,facts]=await Promise.all([researchDb<GeneratedRow[]>(`generated_candidate_hypotheses?disease_id=in.${inDiseases}&status=in.(PROPOSED,REVIEW)&select=id,disease_id,drug_name,drug_normalized_id,relation_type,evidence_count,mean_evidence_quality,confidence,novelty_score`),researchDb<EvidenceRow[]>(`research_evidence?disease_id=in.${inDiseases}&select=id,disease_id,title,evidence_class`),researchDb<ExistingCandidate[]>(`repurposing_candidates?select=disease_id,drug_name`),researchDb<LandscapeFact[]>(`candidate_landscape_facts?select=disease_id,drug_name,drug_normalized_id,fact_type,confidence`)]); if(!generatedRaw.length)return{ranked:0,fastTrack:0,review:0};
  const generated=await deduplicateGenerated(generatedRaw); const evidenceIds=evidence.map(e=>e.id); const relations=evidenceIds.length?await researchDb<RelationRow[]>(`research_evidence_relations?evidence_id=in.(${evidenceIds.join(",")})&select=evidence_id,relation_type,entity1_type,entity1_id,entity1_text,entity2_type,entity2_id,entity2_text`):[]; const evidenceById=new Map(evidence.map(e=>[e.id,e])); const existingPairs=new Set(existing.map(c=>`${c.disease_id}|${normalize(c.drug_name)}`)); const factsByDrug=new Map<string,LandscapeFact[]>(); for(const f of facts){const k=keyFor(f.drug_name,f.drug_normalized_id);const a=factsByDrug.get(k)??[];a.push(f);factsByDrug.set(k,a);}
  const cross=new Map<string,{diseases:Set<string>;evidence:Set<string>;positive:number;negative:number;drugName:string;drugId?:string}>(); for(const r of relations){const d=relationDrug(r);const ev=evidenceById.get(r.evidence_id);if(!d?.name||!ev)continue;const k=keyFor(d.name,d.id);const g=cross.get(k)??{diseases:new Set<string>(),evidence:new Set<string>(),positive:0,negative:0,drugName:d.name,drugId:d.id??undefined};g.diseases.add(ev.disease_id);g.evidence.add(r.evidence_id);const rt=r.relation_type.toUpperCase();if(positiveRelations.has(rt))g.positive++;if(negativeRelations.has(rt))g.negative++;cross.set(k,g);}
  let fastTrack=0,review=0; for(const c of generated){const k=keyFor(c.drug_name,c.drug_normalized_id);const g=cross.get(k);const curatedFacts=(factsByDrug.get(k)??[]).filter(f=>f.disease_id===null||f.disease_id===c.disease_id);const syntheticTrialFact:LandscapeFact|null=c.relation_type==="TRIAL_INTERVENTION"?{disease_id:c.disease_id,drug_name:c.drug_name,drug_normalized_id:c.drug_normalized_id,fact_type:"ACTIVE_TRIAL",confidence:85}:null;const candidateFacts=syntheticTrialFact?[...curatedFacts,syntheticTrialFact]:curatedFacts;const eligibility=assessCandidateEligibility(c.drug_name,candidateFacts);const lp=landscapePenalty(curatedFacts);const positive=g?.positive??0,relationNeg=g?.negative??0;const relationNegative=clamp((relationNeg/Math.max(1,positive+relationNeg))*100);const negativePenalty=clamp(relationNegative*.55+lp.negative*.75);const support=g?.diseases.size??1;const baseline=existingPairs.has(`${c.disease_id}|${normalize(c.drug_name)}`)?65:support>=4?25:support>=2?12:5;const competitionPenalty=clamp(baseline+lp.competition);const exposure=exposureScore(evidence.filter(e=>e.disease_id===c.disease_id),c.drug_name,candidateFacts);const breadth=clamp(25+Math.min(Number(c.evidence_count),8)*9);const readiness=clamp(exposure*.42+Number(c.mean_evidence_quality)*.33+breadth*.20+(candidateFacts.some(f=>["APPROVAL","APPROVED_INDICATION","ACTIVE_TRIAL"].includes(f.fact_type))?10:0));const adjustedNovelty=clamp(Number(c.novelty_score)-competitionPenalty*.60);const crossScore=clamp(30+Math.min(support,5)*12);const rawPrelim=clamp(Number(c.mean_evidence_quality)*.24+Number(c.confidence)*.18+readiness*.22+exposure*.14+adjustedNovelty*.12+crossScore*.10-negativePenalty*.30);let prelim=rawPrelim;let routing=route(prelim,negativePenalty,competitionPenalty);if(!eligibility.eligibleForRepurposing){prelim=Math.min(prelim,30);routing="DEPRIORITIZE";}else if(eligibility.requiresReview&&!["APPROVED_DRUG","CLINICAL_DRUG","INVESTIGATIONAL_DRUG"].includes(eligibility.eligibilityClass)){routing="HOLD";}if(routing==="FAST_TRACK_DRA")fastTrack++;if(routing==="DRA_REVIEW")review++;
    await researchDb<unknown>(`generated_candidate_hypotheses?id=eq.${c.id}`,{method:"PATCH",prefer:"return=minimal",body:{drug_name:eligibility.canonicalName,cross_disease_support:support,negative_evidence_penalty:negativePenalty,competition_penalty:competitionPenalty,human_exposure_score:exposure,development_readiness_score:readiness,novelty_score:adjustedNovelty,preliminary_dra_score:prelim,routing_decision:routing,ranking_version:"CRN-2.2",ranking_rationale:{eligibilityClass:eligibility.eligibilityClass,eligibleForRepurposing:eligibility.eligibleForRepurposing,eligibilityRequiresReview:eligibility.requiresReview,eligibilityConfidence:eligibility.confidence,eligibilityRationale:eligibility.rationale,identitySource:c.drug_normalized_id?"NORMALIZED_ID":"CANONICAL_NAME",clinicalTrialIntervention:c.relation_type==="TRIAL_INTERVENTION",recallEvidenceCount:Number(c.evidence_count),rawPreliminaryDraScore:rawPrelim,crossDiseaseSupport:support,positiveSignals:positive,negativeSignals:relationNeg,humanExposure:exposure,developmentReadiness:readiness,adjustedNovelty,competitionPenalty,negativePenalty,landscapeFacts:candidateFacts.map(f=>f.fact_type)},updated_at:new Date().toISOString()}});}
  return{ranked:generated.length,fastTrack,review};
}
