import { generateCandidateHypotheses } from "./candidate-generation";
import { rankGeneratedCandidatesV2 } from "./candidate-ranking-v2";
import { detectMaterialChanges } from "./change-detection";
import { scoreEvidenceQuality } from "./evidence-quality";
import { detectHypothesisImpacts } from "./hypothesis-change";
import { loadCandidateHypotheses } from "./hypothesis-registry";
import { ingestPubmedDisease } from "./ingestion/pubmed";
import { ingestClinicalTrialsDisease } from "./ingestion/clinical-trials";
import { extractPubTator3, type PubTatorExtraction } from "./ingestion/pubtator3";
import { persistEvidence, persistHypothesisImpacts, persistMaterialChanges, persistPubTatorExtraction } from "./ingestion/persist";
import { resolveEvidenceEntities } from "./ontology";
import { inferEvidenceRelations } from "./relation-inference";

export type EvidenceSource = "PUBMED" | "CLINICAL_TRIALS";
export type ResearchPipelineInput = { diseaseName: string; sources?: EvidenceSource[]; limitPerSource?: number; includePubTator3?: boolean; includeHypothesisDetection?: boolean; includeOntologyResolution?: boolean; includeEvidenceQuality?: boolean; includeCandidateGeneration?: boolean; includeCandidateRankingV2?: boolean; };
const disabledPubTator = (): PubTatorExtraction => ({ entities: [], relations: [], status: "DISABLED", requestedPmids: 0, documentsParsed: 0, batchesRequested: 0, batchesSucceeded: 0, batchesFailed: 0, parseFailures: 0, warnings: [] });

export async function runResearchPipeline(input: ResearchPipelineInput) {
  const diseaseName=input.diseaseName; const sources=input.sources ?? ["PUBMED","CLINICAL_TRIALS"]; const limitPerSource=input.limitPerSource ?? 20;
  const includePubTator3=input.includePubTator3 ?? true; const includeHypothesisDetection=input.includeHypothesisDetection ?? true; const includeOntologyResolution=input.includeOntologyResolution ?? true; const includeEvidenceQuality=input.includeEvidenceQuality ?? true; const includeCandidateGeneration=input.includeCandidateGeneration ?? true; const includeCandidateRankingV2=input.includeCandidateRankingV2 ?? true;
  const results=await Promise.all(sources.map((source)=>source==="PUBMED"?ingestPubmedDisease(diseaseName,limitPerSource):ingestClinicalTrialsDisease(diseaseName,limitPerSource))); const normalized=results.flatMap((result)=>result.normalized); const persistence=await persistEvidence(normalized);
  const pubmedEvidence=normalized.filter((item)=>item.sourceType==="PUBMED"); const pubtator=includePubTator3?await extractPubTator3(pubmedEvidence):disabledPubTator(); const pubtatorPersistence=includePubTator3 && pubtator.entities.length+pubtator.relations.length>0?await persistPubTatorExtraction(diseaseName,pubtator):{entities:0,relations:0}; const pubtatorUsable=pubtator.status==="SUCCESS"||pubtator.status==="PARTIAL";
  const ontology=includeOntologyResolution&&includePubTator3&&pubtator.entities.length>0?await resolveEvidenceEntities(diseaseName):{examined:0,resolved:0,externalId:0,alias:0};
  const evidenceQuality=includeEvidenceQuality?await scoreEvidenceQuality(diseaseName):{scored:0,scores:[]};
  const relationInference=includeCandidateGeneration&&pubtatorUsable&&pubtator.entities.length>0?await inferEvidenceRelations(diseaseName):{inferred:0,evidenceWithSignals:0};
  const changes=detectMaterialChanges(normalized,pubtator); const changePersistence=await persistMaterialChanges(diseaseName,changes); const hypotheses=includeHypothesisDetection?await loadCandidateHypotheses(diseaseName):[]; const hypothesisImpacts=includeHypothesisDetection?detectHypothesisImpacts(normalized,pubtator,hypotheses):[]; const hypothesisPersistence=includeHypothesisDetection?await persistHypothesisImpacts(diseaseName,hypothesisImpacts):{logged:0};
  const generatedCandidates=includeCandidateGeneration&&pubtatorUsable&&pubtator.entities.length>0?await generateCandidateHypotheses(diseaseName):{generated:0,candidates:[]}; const candidateRankingV2=includeCandidateRankingV2&&includeCandidateGeneration&&pubtatorUsable?await rankGeneratedCandidatesV2(diseaseName):{ranked:0,fastTrack:0,review:0};
  return { diseaseName,fetched:results.reduce((sum,result)=>sum+result.fetched,0),normalized:normalized.length,persisted:persistence.inserted,skippedUnknownDisease:persistence.skippedUnknownDisease,
    pubtator3:{enabled:includePubTator3,status:pubtator.status,requestedPmids:pubtator.requestedPmids,documentsParsed:pubtator.documentsParsed,batchesRequested:pubtator.batchesRequested,batchesSucceeded:pubtator.batchesSucceeded,batchesFailed:pubtator.batchesFailed,parseFailures:pubtator.parseFailures,warnings:pubtator.warnings,entitiesExtracted:pubtator.entities.length,relationsExtracted:pubtator.relations.length,entitiesPersisted:pubtatorPersistence.entities,relationsPersisted:pubtatorPersistence.relations},
    relationInference:{enabled:includeCandidateGeneration,method:"COOCCURRENCE_V2",inferred:relationInference.inferred,evidenceWithSignals:relationInference.evidenceWithSignals,causal:false}, ontology:{enabled:includeOntologyResolution,...ontology}, evidenceQuality:{enabled:includeEvidenceQuality,scored:evidenceQuality.scored,meanComposite:evidenceQuality.scores.length?Math.round((evidenceQuality.scores.reduce((sum,score)=>sum+score.compositeScore,0)/evidenceQuality.scores.length)*10)/10:0,highQuality:evidenceQuality.scores.filter((score)=>score.compositeScore>=75).length},
    materialChanges:{logged:changePersistence.logged,red:changes.filter((change)=>change.severity==="RED").length,amber:changes.filter((change)=>change.severity==="AMBER").length,green:changes.filter((change)=>change.severity==="GREEN").length,reviewRequired:changes.filter((change)=>change.materialReviewRequired).length}, hypothesisChanges:{enabled:includeHypothesisDetection,registryDriven:true,hypothesesEvaluated:hypotheses.length,impactsLogged:hypothesisPersistence.logged,strengthen:hypothesisImpacts.filter((impact)=>impact.direction==="STRENGTHEN").length,weaken:hypothesisImpacts.filter((impact)=>impact.direction==="WEAKEN").length,kill:hypothesisImpacts.filter((impact)=>impact.direction==="KILL").length,neutral:hypothesisImpacts.filter((impact)=>impact.direction==="NEUTRAL").length,hardGateCandidates:hypothesisImpacts.filter((impact)=>impact.hardGateCandidate).length,humanReviewRequired:hypothesisImpacts.filter((impact)=>impact.requiresHumanReview).length,proposedDraDelta:hypothesisImpacts.reduce((sum,impact)=>sum+impact.proposedDraDelta,0),proposedRdiaDelta:hypothesisImpacts.reduce((sum,impact)=>sum+impact.proposedRdiaDelta,0)},
    candidateGeneration:{enabled:includeCandidateGeneration,blockedByExtraction:includeCandidateGeneration&&!pubtatorUsable,generated:generatedCandidates.generated,reviewReady:generatedCandidates.candidates.filter((candidate)=>candidate.generationScore>=70).length,topScore:generatedCandidates.candidates[0]?.generationScore??0}, candidateRankingV2:{enabled:includeCandidateRankingV2,blockedByExtraction:includeCandidateRankingV2&&!pubtatorUsable,ranked:candidateRankingV2.ranked,fastTrackDra:candidateRankingV2.fastTrack,draReview:candidateRankingV2.review,version:"CRN-2.0"},sources:results.map((result)=>({source:result.source,fetched:result.fetched,normalized:result.normalized.length})) };
}
