import { generateCandidateHypotheses } from "./candidate-generation";
import { rankGeneratedCandidatesV2 } from "./candidate-ranking-v2";
import { detectMaterialChanges } from "./change-detection";
import { persistClinicalTrialInterventionSignals } from "./clinical-trial-interventions";
import { scoreEvidenceQuality } from "./evidence-quality";
import { detectHypothesisImpacts } from "./hypothesis-change";
import { loadCandidateHypotheses } from "./hypothesis-registry";
import { ingestPubmedDisease } from "./ingestion/pubmed";
import { ingestClinicalTrialsDisease } from "./ingestion/clinical-trials";
import { extractPubTator3, type PubTatorExtraction } from "./ingestion/pubtator3";
import { persistEvidence, persistHypothesisImpacts, persistMaterialChanges, persistPubTatorExtraction } from "./ingestion/persist";
import { resolveEvidenceEntities } from "./ontology";
import { inferEvidenceRelations } from "./relation-inference";

export type EvidenceSource="PUBMED"|"CLINICAL_TRIALS"; export type ResearchPipelineInput={diseaseName:string;sources?:EvidenceSource[];limitPerSource?:number;includePubTator3?:boolean;includeHypothesisDetection?:boolean;includeOntologyResolution?:boolean;includeEvidenceQuality?:boolean;includeCandidateGeneration?:boolean;includeCandidateRankingV2?:boolean};
const disabledPubTator=():PubTatorExtraction=>({entities:[],relations:[],status:"DISABLED",requestedPmids:0,documentsParsed:0,batchesRequested:0,batchesSucceeded:0,batchesFailed:0,parseFailures:0,warnings:[]});
export async function runResearchPipeline(input:ResearchPipelineInput){
 const diseaseName=input.diseaseName,sources=input.sources??["PUBMED","CLINICAL_TRIALS"],limitPerSource=input.limitPerSource??20,includePubTator3=input.includePubTator3??true,includeHypothesisDetection=input.includeHypothesisDetection??true,includeOntologyResolution=input.includeOntologyResolution??true,includeEvidenceQuality=input.includeEvidenceQuality??true,includeCandidateGeneration=input.includeCandidateGeneration??true,includeCandidateRankingV2=input.includeCandidateRankingV2??true;
 const results=await Promise.all(sources.map(source=>source==="PUBMED"?ingestPubmedDisease(diseaseName,limitPerSource):ingestClinicalTrialsDisease(diseaseName,limitPerSource)));const normalized=results.flatMap(r=>r.normalized),persistence=await persistEvidence(normalized);
 const trialSignals=sources.includes("CLINICAL_TRIALS")?await persistClinicalTrialInterventionSignals(diseaseName,limitPerSource):{interventions:0,relations:0};
 const pubmedEvidence=normalized.filter(i=>i.sourceType==="PUBMED"),pubtator=includePubTator3?await extractPubTator3(pubmedEvidence):disabledPubTator(),pubtatorPersistence=includePubTator3&&pubtator.entities.length+pubtator.relations.length>0?await persistPubTatorExtraction(diseaseName,pubtator):{entities:0,relations:0},pubtatorUsable=pubtator.status==="SUCCESS"||pubtator.status==="PARTIAL";
 const ontology=includeOntologyResolution&&includePubTator3&&pubtator.entities.length>0?await resolveEvidenceEntities(diseaseName):{examined:0,resolved:0,externalId:0,alias:0},evidenceQuality=includeEvidenceQuality?await scoreEvidenceQuality(diseaseName):{scored:0,scores:[]},relationInference=includeCandidateGeneration&&pubtatorUsable&&pubtator.entities.length>0?await inferEvidenceRelations(diseaseName):{inferred:0,evidenceWithSignals:0};
 const changes=detectMaterialChanges(normalized,pubtator),changePersistence=await persistMaterialChanges(diseaseName,changes),hypotheses=includeHypothesisDetection?await loadCandidateHypotheses(diseaseName):[],hypothesisImpacts=includeHypothesisDetection?detectHypothesisImpacts(normalized,pubtator,hypotheses):[],hypothesisPersistence=includeHypothesisDetection?await persistHypothesisImpacts(diseaseName,hypothesisImpacts):{logged:0};
 const generatedCandidates=includeCandidateGeneration&&(pubtatorUsable||trialSignals.relations>0)?await generateCandidateHypotheses(diseaseName):{generated:0,candidates:[]},candidateRankingV2=includeCandidateRankingV2&&includeCandidateGeneration?await rankGeneratedCandidatesV2(diseaseName):{ranked:0,fastTrack:0,review:0,benchmarks:0};
 return{diseaseName,fetched:results.reduce((s,r)=>s+r.fetched,0),normalized:normalized.length,persisted:persistence.inserted,skippedUnknownDisease:persistence.skippedUnknownDisease,retrieval:{version:"ER-2.0",pubmedBroadAndTherapeutic:true,clinicalTrialInterventions:trialSignals.interventions,clinicalTrialRelations:trialSignals.relations},pubtator3:{enabled:includePubTator3,status:pubtator.status,requestedPmids:pubtator.requestedPmids,documentsParsed:pubtator.documentsParsed,batchesRequested:pubtator.batchesRequested,batchesSucceeded:pubtator.batchesSucceeded,batchesFailed:pubtator.batchesFailed,parseFailures:pubtator.parseFailures,warnings:pubtator.warnings,entitiesExtracted:pubtator.entities.length,relationsExtracted:pubtator.relations.length,entitiesPersisted:pubtatorPersistence.entities,relationsPersisted:pubtatorPersistence.relations},relationInference:{enabled:includeCandidateGeneration,method:"COOCCURRENCE_V2",inferred:relationInference.inferred,evidenceWithSignals:relationInference.evidenceWithSignals,causal:false},ontology:{enabled:includeOntologyResolution,...ontology},evidenceQuality:{enabled:includeEvidenceQuality,scored:evidenceQuality.scored,meanComposite:evidenceQuality.scores.length?Math.round((evidenceQuality.scores.reduce((s,x)=>s+x.compositeScore,0)/evidenceQuality.scores.length)*10)/10:0,highQuality:evidenceQuality.scores.filter(x=>x.compositeScore>=75).length},materialChanges:{logged:changePersistence.logged,red:changes.filter(x=>x.severity==="RED").length,amber:changes.filter(x=>x.severity==="AMBER").length,green:changes.filter(x=>x.severity==="GREEN").length,reviewRequired:changes.filter(x=>x.materialReviewRequired).length},hypothesisChanges:{enabled:includeHypothesisDetection,registryDriven:true,hypothesesEvaluated:hypotheses.length,impactsLogged:hypothesisPersistence.logged,strengthen:hypothesisImpacts.filter(x=>x.direction==="STRENGTHEN").length,weaken:hypothesisImpacts.filter(x=>x.direction==="WEAKEN").length,kill:hypothesisImpacts.filter(x=>x.direction==="KILL").length,neutral:hypothesisImpacts.filter(x=>x.direction==="NEUTRAL").length,hardGateCandidates:hypothesisImpacts.filter(x=>x.hardGateCandidate).length,humanReviewRequired:hypothesisImpacts.filter(x=>x.requiresHumanReview).length,proposedDraDelta:hypothesisImpacts.reduce((s,x)=>s+x.proposedDraDelta,0),proposedRdiaDelta:hypothesisImpacts.reduce((s,x)=>s+x.proposedRdiaDelta,0)},candidateGeneration:{enabled:includeCandidateGeneration,generated:generatedCandidates.generated,reviewReady:generatedCandidates.candidates.filter(c=>c.generationScore>=70).length,topScore:generatedCandidates.candidates[0]?.generationScore??0},candidateRankingV2:{enabled:includeCandidateRankingV2,ranked:candidateRankingV2.ranked,fastTrackDra:candidateRankingV2.fastTrack,draReview:candidateRankingV2.review,benchmarks:candidateRankingV2.benchmarks,version:"CRN-2.3"},sources:results.map(r=>({source:r.source,fetched:r.fetched,normalized:r.normalized.length}))};
}
